import Head from "next/head";
import Menu from "../components/Menu";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <main className={styles.main}></main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
