import Head from "next/head";

import MainLayout from "../components/layouts/MainLayout";

import styles from "../styles/Home.module.css";

export default function Home({ offers }) {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <h1>home</h1>
        <div className={styles.container}>
          <main className={styles.main}>
            {offers &&
              offers.map((offer) => (
                <div
                  key={`offer-${offer.id}`}
                  className={styles.offersContainer}
                >
                  <div>
                    <img src={offer.cover} alt="aa" />
                  </div>
                  <h3>{offer.name}</h3>
                  <p>
                    {offer.street}, {offer.postal__code} {offer.city}
                  </p>
                </div>
              ))}
          </main>
          <footer className={styles.footer}></footer>
        </div>
      </MainLayout>
    </>
  );
}
export async function getServerSideProps() {
  const response = await fetch("http://localhost:3000/api/offers");
  const data = await response.json();

  return {
    props: {
      offers: data,
    },
  };
}
