import Head from "next/head";
import MainLayout from "../components/layouts/MainLayout";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <h1>home</h1>
        <div className={styles.container}>
          <main className={styles.main}></main>
          <footer className={styles.footer}></footer>
        </div>
      </MainLayout>
    </>
  );
}
